"""Add TokenDenylist model

Revision ID: 6372783363d4
Revises: e4779af9c308
Create Date: 2025-08-20 17:27:11.687719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6372783363d4'
down_revision = 'e4779af9c308'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_denylist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    , sa.UniqueConstraint('jti', name='uq_tokendenylist_jti'))
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_courses_name', ['name'])

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_sessions_lecturer_id', 'users', ['lecturer_id'], ['id'])

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_students_user_id', ['user_id'])
        batch_op.create_unique_constraint('uq_students_email', ['email'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_users_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('uq_users_email', type_='unique')

    with op.batch_alter_table('students', schema=None) as batch_op:
        batch_op.drop_constraint('uq_students_user_id', type_='unique')
        batch_op.drop_constraint('uq_students_email', type_='unique')

    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sessions_lecturer_id', type_='foreignkey')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_courses_name', type_='unique')

    op.drop_table('token_denylist')
    # ### end Alembic commands ###
