"""Fix Session model relationship and remove redundant lecturer_id

Revision ID: 83488330c12b
Revises: a1e7546d783d
Create Date: 2025-09-11 11:17:20.747555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83488330c12b'
down_revision = 'a1e7546d783d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_column('lecturer_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lecturer_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_sessions_lecturer_id_users', 'users', ['lecturer_id'], ['id'])

    # ### end Alembic commands ###
